export const dataNotes = [
  {
    _id: 1,
    title: 'Title 1',
    content: `Lorem ipsum dolor sit amet consectetur adipisicing elit.
       Eius suscipit obcaecati fugiat minus est. Quod porro delectus, temporibus corrupti voluptatem sunt 
       velit iure accusamus veniam aliquam pariatur laborum amet natus?`,
    thumnail: '',
    background: 'rgb(255, 115, 22)',
    themes: ['Pins', 'ReactJs', 'NodeJs'],
    user: {
      _id: '2',
      __v: 1,
      avatar: '',
      status: 'active',
      type: 'register',
      username: '',
      password: '',
      email: '',
      createdAt: '',
      updatedAt: '',
      role: 'customer',
      slug: '',
    },
  },
  {
    _id: 2,
    title: 'Title 2',
    content: `Lorem ipsum dolor sit amet consectetur adipisicing elit.
       Eius suscipit obcaecati fugiat minus est. Quod porro delectus, temporibus corrupti voluptatem sunt 
       velit iure accusamus veniam aliquam pariatur laborum amet natus?`,
    thumnail: '',
    background: '#e74c3c',
    themes: ['Pins'],
    user: {
      _id: '2',
      __v: 1,
      avatar: '',
      status: 'active',
      type: 'register',
      username: '',
      password: '',
      email: '',
      createdAt: '',
      updatedAt: '',
      role: 'customer',
      slug: '',
    },
  },
  {
    _id: 3,
    title: 'Title 3',
    content: `Lorem ipsum dolor sit amet consectetur adipisicing elit.
       Eius suscipit obcaecati fugiat minus est. Quod porro delectus, temporibus corrupti voluptatem sunt 
       velit iure accusamus veniam aliquam pariatur laborum amet natus?`,
    thumnail: '',
    background: '#a55eea',
    themes: ['ReactJs'],
    user: {
      _id: '2',
      __v: 1,
      avatar: '',
      status: 'active',
      type: 'register',
      username: '',
      password: '',
      email: '',
      createdAt: '',
      updatedAt: '',
      role: 'customer',
      slug: '',
    },
  },
  {
    _id: 4,
    title: 'Title 4',
    content: `Lorem ipsum dolor sit amet consectetur adipisicing elit.
       Eius suscipit obcaecati fugiat minus est. Quod porro delectus, temporibus corrupti voluptatem sunt 
       velit iure accusamus veniam aliquam pariatur laborum amet natus?`,
    thumnail: '',
    background: '#a5b1c2',
    themes: ['ReactJs'],
    user: {
      _id: '2',
      __v: 1,
      avatar: '',
      status: 'active',
      type: 'register',
      username: '',
      password: '',
      email: '',
      createdAt: '',
      updatedAt: '',
      role: 'customer',
      slug: '',
    },
  },
  {
    _id: 5,
    title: 'Title 5',
    content: `Lorem ipsum dolor sit amet consectetur adipisicing elit.
       Eius suscipit obcaecati fugiat minus est. Quod porro delectus, temporibus corrupti voluptatem sunt 
       velit iure accusamus veniam aliquam pariatur laborum amet natus?`,
    thumnail: '',
    background: '',
    themes: ['ReactJs'],
    user: {
      _id: '2',
      __v: 1,
      avatar: '',
      status: 'active',
      type: 'register',
      username: '',
      password: '',
      email: '',
      createdAt: '',
      updatedAt: '',
      role: 'customer',
      slug: '',
    },
  },
  {
    _id: 6,
    title: 'Title 6',
    content: `Lorem ipsum dolor sit amet consectetur adipisicing elit.
       Eius suscipit obcaecati fugiat minus est. Quod porro delectus, temporibus corrupti voluptatem sunt 
       velit iure accusamus veniam aliquam pariatur laborum amet natus?`,
    thumnail: '',
    background: '',
    themes: ['ReactJs'],
    user: {
      _id: '2',
      __v: 1,
      avatar: '',
      status: 'active',
      type: 'register',
      username: '',
      password: '',
      email: '',
      createdAt: '',
      updatedAt: '',
      role: 'customer',
      slug: '',
    },
  },
  {
    _id: 7,
    title: 'Title 7',
    content: `Lorem ipsum dolor sit amet consectetur adipisicing elit.
       Eius suscipit obcaecati fugiat minus est. Quod porro delectus, temporibus corrupti voluptatem sunt 
       velit iure accusamus veniam aliquam pariatur laborum amet natus?`,
    thumnail: '',
    background: '',
    themes: ['Typescript'],
    user: {
      _id: '2',
      __v: 1,
      avatar: '',
      status: 'active',
      type: 'register',
      username: '',
      password: '',
      email: '',
      createdAt: '',
      updatedAt: '',
      role: 'customer',
      slug: '',
    },
  },
];

export const dataThemes = [
  {
    _id: 100,
    title: 'ReactJs',
  },
  { id: 101, title: 'Pins' },
  { id: 102, title: 'Typescript' },
];
